steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/appsflyer-pull-data:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/appsflyer-pull-data:$COMMIT_SHA']
images:
  - 'gcr.io/$PROJECT_ID/appsflyer-pull-data:$COMMIT_SHA'