---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [ main ]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: appsflyer-api-pull
      PROJECT_ID: maximizer-omega
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true
#aaa
    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Configure Docker Client
      run: |-
        gcloud auth configure-docker --quiet
        gcloud auth configure-docker asia-northeast3-docker.pkg.dev

    - name: Push Docker Image to Artifact Registry
      env:
        GIT_TAG: V.0.1.0
      run: |-
        docker tag $IMAGE_NAME:latest asia-northeast3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker tag $IMAGE_NAME:latest asia-northeast3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG
        docker push asia-northeast3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:latest
        docker push asia-northeast3-docker.pkg.dev/$PROJECT_ID/images/$IMAGE_NAME:$GIT_TAG